### ISSUE TITLE
Autoplay Hover Issue

### ISSUE THREAD

**Issue by allmon01** [fredleblanc/roundabout#1]
When having roundabout stop autoplay on hover, and then firing the stopAutoplay method. All is well unless you mouseover the roundabout then the autoplay starts again. Which isn't a terrible thing. I'm sure I can write something to take care of this but I would just assume if I had stopped autoplay it would not start up again unless I restarted it. Either way I'm very pleased with this plugin.

**Comment by fredleblanc** [comment]
For clarity on this: `stopAutoplay` now accepts an optional `keepAutoplayBindings` parameter that (when `false`, which is the default if you leave it empty) will destroy any automatically set autoplay `mouseenter` and `mouseleave` bindings. This way, you can use `stopAutoplay` as you were before and you'll now get the expected result, or if you _do_ want to only "pause" instead of "stop" completely, you can do that too.
