### ISSUE TITLE
How to update roundabout dynamically

### ISSUE THREAD

**Issue by MikeA94** [fredleblanc/roundabout#10]
Hi,
 My UL is dynamically built, as I add LI items on the fly (After Init of roundabout). When I do this , the layout is not correct in the control. How do I force a recalc of the layout when a LI is added dynamically? I tried $("#MyUL").roundabout("relayoutChildren");   but that did not have any effect.

Thanks,
 Mike

**Comment by fredleblanc** [comment]
Just to clarify, you can now do something like this (assuming Roundabout is already tied to the `ul`):

``` javascript
$(document).ready(function() {
    // add a link, this would be in a link's click event, for example
    $("ul")
        .append("<li>New element.</li>")
        .roundabout("relayoutChildren");
});
```

And the same goes for removing elements.

**Comment by MikeA94** [comment]
Thanks Fred,
 I downloaded new version and I can add LI items dynamically now. (However the UL must have at least one LI specified in the HTML file to work properly). If I try for example to add 5 LI items to an empty UL (roundabout) it does not work. I was able to get around that by placing a temp LI in the UL in the html file.  (Then removing it later)
My issue now is that if the UL has only 2 LI items, I never see the 2nd item. I assume its behind the first LI item? Once I add a third LI item i can see all 3 fine. Is there a way to view all (2) LI items when there is only 2 LI items in the UL?

thanks,
Mike

**Comment by fredleblanc** [comment]
Due to the nature of how Roundabout works, you'll probably want at least three items for things to look nice. Roundabout will evenly position the moving elements along the shape, and with two elements, that means one in the front and one in the back.

You could try using different shapes from Roundabout Shapes, but that probably won't help if you're looking for a circle. Another thought is you could have a third element with nothing in it, and then rig Roundabout to manually skip over it when clicking through the results.

**Comment by MikeA94** [comment]
Thanks,
 I understand. I will think of something , maybe simply show the 2 items in a standard UL, and if there is greater than 2 items use Roundabout. 
Thanks for your help and great job on Roundabout.

Mike
