### ISSUE TITLE
enableDrag

### ISSUE THREAD

**Issue by Alexwijn** [fredleblanc/roundabout#3]
Hello,

I used the demo script to get my Roundabout able to drag.
But the issue is that if you drag it to a position and then drag it again it goes to the first row again.
So if you have a lot of LI's in the roundabout and enable dragging, you can never reach that.

Let me know when this is fixed.

Thanks,
Alexw

**Comment by fredleblanc** [comment]
Can you provide a link to an example?

**Comment by Alexwijn** [comment]
This one for example:
http://dekaartenbox.eu/filter-overview-algemeen.html

I also enabled the 3D stuff, but got only one problem there.
If you move over on "Producten" and then move to a item that is above the Roundabout the navigation menu disappears.
I tryd playing with the Z-Index but that did not work either, any sollution for that.

Thanks,
Alexw

**Comment by fredleblanc** [comment]
Ah ha! It seems that for the drop event to fire successfully, your Roundabout needs to have a height defined. Can you try adding a height and seeing if it works?

**Comment by Alexwijn** [comment]
Ok that fix the draggin problem.
Now only 2 problems remains:
- The "Producten" menu disapeares when you go over a link that is above the Roundabout
- The cards are not clickable when its dragable

**Comment by fredleblanc** [comment]
Sorry, accidentally hit a keyboard shortcut that closes this issue apparently…

The first bullet point looks like a z-index problem, although the 3D-effect seems to cause things to poke through the menu regardless of z-index. (And that very well could be how browsers are working at the moment, or it could be due to the perspective setting, I'm not sure on those. You may want to scrap 3D here.)

The second bullet point, on this page: http://dekaartenbox.eu/filter-overview-sarah.html I'm able to both click and drag fine. Again, this may be due to the 3D rendering and where clickable areas are.

**Comment by Alexwijn** [comment]
Ok, thanks for the quick reply. I hope the 3D functionality will be fixed somewhere in the furture.
For now I will use it without. Thanks again.
