### ISSUE TITLE
using background images for li elements doesn't get scaled

### ISSUE THREAD

**Issue by bnowacky** [fredleblanc/roundabout#59]
If you use a background image on the li element, it gets cropped when moved to positions other than in-focus.  With my layout, I need to use background images rather than regular images in the li, but can't seem to see anyway to make this work.

**Comment by fredleblanc** [comment]
If you want to use background images, you'll want to set background-size in CSS. Keep in mind that this property isn't supported well in non-current versions of IE. Otherwise, you can set "background images" as normal inline images that are positioned absolutely, width 100%, z-indexed below the rest of your content.

**Comment by bnowacky** [comment]
Tried that, but as soon as you drag the in-focus element away, it jumps immediately to roundabout-moveable-item, and looks horrible. There's no in-between state of 'animating' or 'moving'....

**Comment by bnowacky** [comment]
conversely, if the images to the left and right of 'in-focus' had an alternate style element the background-image size element would be perfect.

**Comment by bnowacky** [comment]
FWIW, this made it work: 

Ln 499: 'background-size': factors.width + "px " + factors.height + "px", Doesn't cause any choppy animation either. Not sure if that's what you meant with your original suggestion, but works like a charm :)

Thanks for the help !

**Comment by fredleblanc** [comment]
Not what I meant, but hey, if it works, it works! :)
