### ISSUE TITLE
Opera Support is very... Jumpy

### ISSUE THREAD

**Issue by corysimmons** [fredleblanc/roundabout#9]
I'm sure this is a problem with Opera's rendering engine, but it's very jumpy. Doesn't bother me that much, just curious if this was a known problem or if I'm the only one with this issue.

**Comment by fredleblanc** [comment]
From my experience, this is just the speed of the current Opera JavaScript engine. Roundabout does quite a few calculations on each step, and even though I've spent time optimizing things, it's still pretty intense.

So: I think the issue is Opera at the moment. Closing this one for now, unless we find some proof otherwise.
